import type { NextPage } from "next";
import Head from "next/head";
import { Timer } from "../components/timer";

const Home: NextPage = () => {
  return (
    <div className="h-full bg-[url('../public/anime-study.gif')] bg-cover bg-blend-multiply bg-[#333] bg-center ">
      <style jsx global>{`
        body,
        #__next {
          height: 100vh;
        }
      `}</style>
      <Head>
        <title>Pomodoro Timer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full">
        <div className="flex flex-col justify-center items-center h-full">
          <h1 className="text-3xl text-center text-white p-4 m-4">
            Pomodoro Timer
          </h1>
          <Timer />
        </div>
      </main>
    </div>
  );
};

export default Home;
