import type { NextPage } from "next";
import Head from "next/head";
import { Timer } from "../components/timer";

const Home: NextPage = () => {
  return (
    <div className="bg-bgdark h-full">
      <style jsx global>{`
        body,
        #__next {
          height: 100vh;
        }
      `}</style>
      <Head>
        <title>Pomodoro Timer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full">
        <h1 className="text-3xl text-center text-white ">Pomodoro Timer</h1>
        <div className="flex flex-col justify-center items-center h-80">
          <Timer />
        </div>
      </main>
    </div>
  );
};

export default Home;
